### PR TITLE
No GPU device. Resolves #94.

### LINKED ISSUE #94: Running on CPU when configured with CUBLAS
Hello Slate team,

We are using Slate through PETSc which is the computational backend of MOOSE, and we always want to configure PETSc with CUDA to make a unified container for all of our environments. However, we are noticing that PETSc configured with CUDA does not run on a non-GPU environment (no CUDA driver) as Slate is attempting to query the number of devices whenever it is configured with cuBLAS.

Is it possible to allow Slate to run on CPUs even when it is configured with cuBLAS? In other words, I wonder if it would be harmful to add a third condition of not detecting the driver in `device_utils.cc:get_device_count`?

Thanks.

### PR DESCRIPTION
**Pull request by mgates3**
See #94.

### CODE REVIEW

**Review by mgates3 — COMMENTED** [review]
Reviewed.

**Comment by lindsayad** [comment]
Would it be possible for you guys to update the blaspp submodule hash in slate to include this change? Then I will update slate in PETSc

**Comment by mgates3** [comment]
@lindsayad I updated SLATE's master branch in https://github.com/icl-utk-edu/slate/pull/220. Let me know if that works for you.

**Comment by lindsayad** [comment]
That's great, thank you!

**Pull request merged**
